### ISSUE TITLE
Landingpage icons are not shown in Firefox 48 and 49

### ISSUE THREAD

**Issue by derfalx** [Linux-statt-Windows/landingpage#4]
Currently the Icons on the Landingpage are not shown when using Firefox 48 on Manjaro and 49 on Win 10. 
Firebug logs the following two errors:

```
downloadable font: download failed (font-family: "Ionicons" style:normal weight:normal stretch:normal src index:1): content blocked source: https://code.ionicframework.com/ionicons/2.0.1/fonts/ionicons.ttf?v=2.0.1
https://linux-statt-windows.org/assets/font/ionicons.min.css
Line 11
```

```
downloadable font: download failed (font-family: "Ionicons" style:normal weight:normal stretch:normal src index:2): content blocked source: https://code.ionicframework.com/ionicons/2.0.1/fonts/ionicons.woff?v=2.0.1
https://linux-statt-windows.org/assets/font/ionicons.min.css
Line 11
```

Those errors occure aside of two warnings:

```
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped.
https://linux-statt-windows.org/assets/font/ionicons.min.css
Line 11
```

```
Error in parsing value for 'background'.  Declaration dropped.
https://linux-statt-windows.org/css/style.css
Line 42
```

I checked wether it works with Google-Chrome or not, and it works without any problems. So I would say it's a Firefox specific problem.

**Comment by verymilan** [comment]
I cannot confirm this with both versions of Firefox.
May you block the icons somehow?

**Comment by derfalx** [comment]
Just checked some interleaved settings of firefox' noscript-plugin and found a setting specialized on loading fonts. There the fonts have been blocked. Since it's fixed by unblocking the fonts, I'll close this issue
